# Generated by Django 2.0.3 on 2019-08-07 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apiloja', '0002_marca'),
    ]

    operations = [
        migrations.CreateModel(
            name='Processador',
            fields=[
                ('isnProcessador', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=255)),
                ('isnMarca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='apiloja.Marca')),
            ],
        ),
    ]
