# Generated by Django 2.0.3 on 2019-08-07 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiloja', '0003_processador'),
    ]

    operations = [
        migrations.RenameField(
            model_name='processador',
            old_name='isnMarca',
            new_name='marca',
        ),
    ]
