# Generated by Django 2.0.3 on 2019-08-07 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apiloja', '0004_auto_20190807_1523'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlacaMae',
            fields=[
                ('isnPlacaMae', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=255)),
                ('slots_memoria', models.PositiveIntegerField(default=2)),
                ('total_memoria', models.PositiveIntegerField(default=0)),
                ('video_integrado', models.BooleanField(default=True)),
                ('marca_processador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='apiloja.Marca')),
            ],
        ),
    ]
