# Generated by Django 2.0.3 on 2019-08-07 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apiloja', '0005_placamae'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemoriaRam',
            fields=[
                ('isnMemoriaRam', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TamanhoMemoria',
            fields=[
                ('isnTamanhoMemoria', models.AutoField(primary_key=True, serialize=False)),
                ('tamanho', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='placamae',
            name='video_integrado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='memoriaram',
            name='tamanho',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='apiloja.TamanhoMemoria'),
        ),
    ]
