# Generated by Django 2.0.3 on 2019-08-07 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apiloja', '0006_auto_20190807_1554'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memoriaram',
            name='descricao',
        ),
        migrations.AddField(
            model_name='memoriaram',
            name='marca',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='apiloja.Marca'),
        ),
    ]
