# Generated by Django 2.0.3 on 2019-08-07 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiloja', '0007_auto_20190807_1600'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlacaVideo',
            fields=[
                ('isnPlacaVideo', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=255)),
            ],
        ),
    ]
