# Generated by Django 2.0.3 on 2019-08-07 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apiloja', '0008_placavideo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maquina',
            fields=[
                ('isnPlacaVideo', models.AutoField(primary_key=True, serialize=False)),
                ('placa_mae', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='apiloja.PlacaMae')),
                ('processador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='apiloja.Processador')),
            ],
        ),
    ]
