# Generated by Django 2.0.3 on 2019-08-07 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apiloja', '0011_maquina_plca_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maquina',
            name='plca_video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='apiloja.PlacaVideo'),
        ),
    ]
