# Generated by Django 2.0.3 on 2019-08-07 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apiloja', '0012_auto_20190807_2049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maquina',
            name='plca_video',
        ),
        migrations.AddField(
            model_name='maquina',
            name='placa_video',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='apiloja.PlacaVideo'),
        ),
    ]
