# Generated by Django 2.0.3 on 2019-08-07 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apiloja', '0013_auto_20190807_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maquina',
            name='placa_video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='apiloja.PlacaVideo'),
        ),
    ]
