# Generated by Django 2.0.3 on 2019-08-16 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apigihtub', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repo',
            name='user_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
