# Generated by Django 2.0.3 on 2019-08-16 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apigihtub', '0003_auto_20190816_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repo',
            name='owner',
            field=models.IntegerField(),
        ),
    ]
