# Generated by Django 2.0.3 on 2019-08-05 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='driector',
            new_name='director',
        ),
    ]
