# Generated by Django 2.0.3 on 2019-08-05 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_auto_20190805_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
    ]
